name       : vulkan
version    : 1.1.73.0
release    : 10
source     :
    - https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/archive/sdk-1.1.73.0.tar.gz : ab6bd8162b246bc5d73dcfb3b69ed7a35b12b739735493f47304b0fc852463e1
license    : Apache-2.0
component  : xorg.graphics
libsplit   : no
emul32     : yes
summary    : Khronos Vulkan ICD loader
description: |
    Vulkan is an Explicit API, enabling direct control over how GPUs actually work. No (or very little) validation or error checking is done inside a Vulkan driver. Applications have full control and responsibility. Any errors in how Vulkan is used often result in a crash. This project provides standard validation layers that can be enabled to ease development by helping developers verify their applications correctly use the Vulkan API.
    Vulkan supports multiple GPUs and multiple global contexts (VkInstance). The ICD loader is necessary to support multiple GPUs and the VkInstance level Vulkan commands. Additionally, the loader manages inserting Vulkan layer libraries, including validation layers between the application and the ICD.
builddeps  :
    - pkgconfig32(gl)
    - pkgconfig32(SPIRV-Tools)
    - pkgconfig32(wayland-client)
    - pkgconfig32(x11)
    - pkgconfig32(xcb)
    - pkgconfig32(xrandr)
    - glslang-32bit-devel
    - spirv-headers
setup      : |
    %patch -p1 < $pkgfiles/external-spirv.patch

    echo "#pragma once" > spirv_tools_commit_id.h
    echo "#define SPIRV_TOOLS_COMMIT_ID \"5f53c42a1e24e329c6e02e41cfd24a1cc0f8d22f\"" >> spirv_tools_commit_id.h
    cp spirv_tools_commit_id.h layers\

    # assembler gets awfully unhappy.
    EXTRA32=""
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        export ASFLAGS=--32
        export EXTRA32="-DCMAKE_INSTALL_LIBDIR=lib32"
    fi
    %cmake_ninja -DBUILD_WSI_MIR_SUPPORT=OFF \
           -DBUILD_WSI_WAYLAND_SUPPORT=ON \
           -DBUILD_WSI_XCB_SUPPORT=ON \
           -DBUILD_WSI_XLIB_SUPPORT=ON \
           -DGLSLANG_SPIRV_INCLUDE_DIR=/usr/include/spirv-tools \
           -DBUILD_TESTS=OFF \
           $EXTRA32 \
           -DBUILD_LAYERS=ON \
           -DCMAKE_SKIP_RPATH=True \
           -DCUSTOM_GLSLANG_BIN_ROOT=/usr/bin \
           -DCUSTOM_SPIRV_TOOLS_BIN_ROOT=/usr/bin \
           -DCMAKE_INSTALL_SYSCONFDIR=/usr/share
build      : |
    %ninja_build
install    : |
    %ninja_install
