name       : vulkan
version    : 1.2.131.2
release    : 18
source     :
    - https://github.com/KhronosGroup/Vulkan-Loader/archive/sdk-1.2.131.2.tar.gz : b6fc552687e7f6af3c75e3f788dc772460ec80a973ffc82a317f9ce510ed17ae
license    : Apache-2.0
component  : xorg.display
emul32     : yes
summary    : Vulkan ICD desktop loader (vulkan-loader)
description: |
    This package provides the Khronos official Vulkan ICD desktop loader.
patterns   :
    - /usr/lib64
    - 32bit : /usr/lib32
builddeps  :
    - pkgconfig32(wayland-client)
    - pkgconfig32(x11)
    - pkgconfig32(xrandr)
    - vulkan-headers
setup      : |
    # https://github.com/KhronosGroup/Vulkan-Loader/blob/master/BUILD.md#linux-32-bit-support
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        export ASFLAGS=--32
    fi

    %cmake_ninja \
        -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX% \
        -DBUILD_TESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
