name       : vulkan
version    : 1.1.70
release    : 9
source     :
    - https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/archive/sdk-1.1.70.0.tar.gz : bd30ffe25a0723775ea8427d65e96bbad6f5130674ac6577ec639b54ce811397
license    : Apache-2.0
component  : xorg.graphics
libsplit   : no
emul32     : yes
summary    : Khronos Vulkan ICD loader
description: |
    Vulkan is an Explicit API, enabling direct control over how GPUs actually work. No (or very little) validation or error checking is done inside a Vulkan driver. Applications have full control and responsibility. Any errors in how Vulkan is used often result in a crash. This project provides standard validation layers that can be enabled to ease development by helping developers verify their applications correctly use the Vulkan API.
    Vulkan supports multiple GPUs and multiple global contexts (VkInstance). The ICD loader is necessary to support multiple GPUs and the VkInstance level Vulkan commands. Additionally, the loader manages inserting Vulkan layer libraries, including validation layers between the application and the ICD.
builddeps  :
    - pkgconfig32(gl)
    - pkgconfig32(SPIRV-Tools)
    - pkgconfig32(wayland-client)
    - pkgconfig32(x11)
    - pkgconfig32(xcb)
    - pkgconfig32(xrandr)
    - glslang-32bit-devel
    - spirv-headers
setup      : |
    %patch -p1 < $pkgfiles/external-spirv.patch
    mkdir solusBuildDir && cd solusBuildDir

    echo "#pragma once" >> spirv_tools_commit_id.h
    echo "#define SPIRV_TOOLS_COMMIT_ID \"01f32ee001409893773219d1a0cc8e696287628e\"" >> spirv_tools_commit_id.h

    # assembler gets awfully unhappy.
    EXTRA32=""
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        export ASFLAGS=--32
        export EXTRA32="-DCMAKE_INSTALL_LIBDIR=lib32"
    fi
    %cmake -DBUILD_WSI_MIR_SUPPORT=OFF \
           -DBUILD_WSI_WAYLAND_SUPPORT=ON \
           -DBUILD_WSI_XCB_SUPPORT=ON \
           -DBUILD_WSI_XLIB_SUPPORT=ON \
           -DGLSLANG_SPIRV_INCLUDE_DIR=/usr/include/spirv-tools \
           -DBUILD_TESTS=OFF \
           $EXTRA32 \
           -DBUILD_LAYERS=ON \
           -DCMAKE_SKIP_RPATH=True \
           -DCUSTOM_GLSLANG_BIN_ROOT=/usr/bin \
           -DCUSTOM_SPIRV_TOOLS_BIN_ROOT=/usr/bin \
           -DCMAKE_INSTALL_SYSCONFDIR=/usr/share \
           -GNinja ..
build      : |
    %meson_build
install    : |
    %meson_install
