name       : vulkan
version    : 1.0.42
release    : 5
source     :
    - https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/archive/sdk-1.0.42.0.tar.gz : 305d3070f559a3f5ad332aff285a3ea0618f9d0696cde81a58765fcb5c7c4e42
license    : Apache-2.0
component  : xorg.graphics
summary    : Khronos Vulkan ICD loader
description: |
    Vulkan is an Explicit API, enabling direct control over how GPUs actually work. No (or very little) validation or error checking is done inside a Vulkan driver. Applications have full control and responsibility. Any errors in how Vulkan is used often result in a crash. This project provides standard validation layers that can be enabled to ease development by helping developers verify their applications correctly use the Vulkan API.
    Vulkan supports multiple GPUs and multiple global contexts (VkInstance). The ICD loader is necessary to support multiple GPUs and the VkInstance level Vulkan commands. Additionally, the loader manages inserting Vulkan layer libraries, including validation layers between the application and the ICD.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xrandr)
    - pkgconfig(wayland-client)
    - chrpath
    - glslang-devel
    - spirv-tools-devel
    - spirv-headers
libsplit   : no
setup      : |
    %cmake -DBUILD_WSI_MIR_SUPPORT=OFF \
           -DBUILD_WSI_WAYLAND_SUPPORT=ON . \
           -DGLSLANG_SPIRV_INCLUDE_DIR=/usr/include/spirv-tools \
           -DBUILD_TESTS=OFF \
           -DBUILD_LAYERS=ON
build      : |
    %make
install    : |
    # ICD Loader
    install -D -d -m 00755 $installdir/%libdir%
    install -m 00755 loader/libvulkan.so* $installdir/%libdir%/.

    # Binaries
    install -D -m 00755 demos/vulkaninfo $installdir/usr/bin/vulkaninfo
    install -m 00755 demos/smoketest $installdir/usr/bin/smoketest

    # Layers
    install -D -d -m 00755 $installdir/usr/share/vulkan/explicit_layer.d
    install -D -d -m 00755 $installdir/usr/share/vulkan/implicit_layer.d

    # Layer .so's
    install -D -d -m 00755 $installdir/%libdir%/vulkan
    install -m 00755 layers/*.so $installdir/%libdir%/vulkan/.

    # Fix the jsons
    install -m 00644 layers/linux/*.json $installdir/usr/share/vulkan/explicit_layer.d
    sed 's@./@%libdir%/vulkan/@' -i $installdir/usr/share/vulkan/explicit_layer.d/*.json

    # Utils is needed globally
    mv $installdir/%libdir%/vulkan/libVkLayer_utils.so $installdir/%libdir%/libVkLayer_utils.so

    # nuke rpath - we don't like these.
    chrpath -d $installdir/%libdir%/vulkan/*.so
