name       : vulkan
version    : 1.0.11.1
release    : 2
source     :
    - https://git.solus-project.com/projects/Vulkan-LoaderAndValidationLayers/snapshot/Vulkan-LoaderAndValidationLayers-3ec2613cd47b5cfdd96842dc9fa64011645a340e.tar.gz : 67f8a12104a2adcced08a7b41f8d7f40e35442dd617cefc4a39ae67f013e6df1
license    : Apache-2.0
component  : xorg.graphics
summary    : Khronos Vulkan ICD loader
description: |
    Vulkan is an Explicit API, enabling direct control over how GPUs actually work. No (or very little) validation or error checking is done inside a Vulkan driver. Applications have full control and responsibility. Any errors in how Vulkan is used often result in a crash. This project provides standard validation layers that can be enabled to ease development by helping developers verify their applications correctly use the Vulkan API.
    Vulkan supports multiple GPUs and multiple global contexts (VkInstance). The ICD loader is necessary to support multiple GPUs and the VkInstance level Vulkan commands. Additionally, the loader manages inserting Vulkan layer libraries, including validation layers between the application and the ICD.
builddeps  :
    - pkgconfig(xcb)
    - pkgconfig(x11)
    - pkgconfig(wayland-client)
    - glslang
    - glslang-devel
    - spirv-tools-devel
libsplit   : no
setup      : |
    %cmake -DBUILD_WSI_WAYLAND_SUPPORT=ON . \
           -DGLSLANG_SPIRV_INCLUDE_DIR=/usr/include/spirv-tools \
           -DBUILD_TESTS=OFF \
           -DBUILD_LAYERS=OFF
           
build      : |
    %make
install    : |
    install -D -d -m 00755 $installdir/%libdir%
    install -m 00755 loader/libvulkan.so* $installdir/%libdir%/.
